### ISSUE TITLE
Error when activating the plugin

### ISSUE THREAD

**Issue by vstrelianyi** [kellenmace/headless-block-parser#1]
First I would like to thank you for the plugin and all your videos on youtube - its cool and helpful!

I'm receiving this error after activating the plugin on PHP 7.3.5
when I have switched to PHP 7.4.1  - the error disappeared. You I guess that the plugin needs some compatibility improvements or minimum php requirements

Parse error: syntax error, unexpected ':', expecting ')' in D:\projects\Royal\20201202_savory\backend\app\public\wp-content\plugins\headless-block-parser-main\headless-block-parser.php on line 63

Btw is it possible to add some field to WP admin where we can input  frontend_app_url ?

best regards,
Viktor

**Comment by kellenmace** [comment]
Hey Viktor 👋🏼

Thank you! Glad you're finding my content helpful.

Yes– on line 63, I use an arrow function (a.k.a. a "short closure"), which requires PHP 7.4+. If you want to use the plugin on a project with a PHP version slightly lower than 7.4, you can change that line to this:

```php
add_filter('block_parser_class', function(): string {
    return 'Headless_Block_Parser';
});
```

For the frontend app URL, you could specify a constant in your project's `wp-config.php` file, like this:
`define( 'FRONTEND_APP_URL', 'http://localhost:3000' );`.

...or as you said, you could alternatively save that value in the database. I would recommend using Advanced Custom Fields (https://www.advancedcustomfields.com/resources/options-page/), Carbon Fields (https://carbonfields.net/docs/containers-theme-options/), or a similar custom fields plugin to add your custom field to an options page.

Best of luck! Please let me know if I can help out with anything else. 👍

**Comment by vstrelianyi** [comment]
ok, clear.
thx for your advice.
Added ACF input field to options page - work perfect!

have a nice day!
